

const news = [
    `The stock saw a massive loss of 16.21 percent on October 22 after a whistle-blowers' complaint spooked investors, shaving Rs 53,451 crore from its market valuation.`,
    `Sharekhan is bullish on Sun Pharmaceutical Industries has recommended buy rating on the stock with a target price of Rs 810 in its research report dated May 27, 2021.`,
    `The company reported weak earnings with a 38 percent fall in revenue.`,
    `Under the terms of the acquisition, for every five shares held in Ranbaxy, shareholders are going to receive four of Sun Pharma.`,
    `Aptech Limited, the global career education and training company, has informed the stock exchanges that its wholly owned subsidiary company has received a dividend of an amount of USD 11,202,479 (equivalent to approximately Rs 50.3 crore) from BJB Career Education Co Ltd of China.`,
    `Infosys, the country's second largest software services company, on Wednesday reported an annual increase of 17 per cent in net profit at ₹ 5,076 crore on the back of large contract wins`,
    ` An ET Now Poll had expected the drug maker to report a profit of Rs 1,030 crore in the quarter`,
    `Net income declined sharply to Rs 87.02 crore in the first quarter of 2020-21 fiscal from Rs 1,417.14 crore in the year-ago period.`,
    `Shares in Ranbaxy Laboratories Ltd fell 3.6 per cent on Wednesday, 27 February 2013, down for a second consecutive session, after India's top drugmaker by sales on reported a surprise quarterly loss on product recall charges.`,
    `The company had posted a consolidated net profit of Rs 3.08 crore in the year-ago quarter, Aptech said in a regulatory filing`,
    `Infosys Insider Trading: Based on an extract of the Structured Digital Database related to the financial results of Infosys for the quarter ended June 30, 2020, the Unpublished Price Sensitive Information (UPSI) came into existence on June 29, 2020. Thus, the UPSI period was from June 29, 2020 to July 15, 2020, Sebi said.`,
    `The development comes after a whistleblower reportedly approached Sebi with a document alleging various irregularities by the company, its promoter Dilip Shanghvi and others, they added.`,
    `Sebi fined Shivani Gupta, Sachin Gupta, Amit Garg and Quick Developers a total of Rs 8 crore for alleged unlawful gains by violating insider trading norms.`,
    `The Securities Appellate Tribunal (SAT) has upheld insider trading charges against VK Kaul, a former independent director of Ranbaxy, and his wife Bala Kaul, accusing them of insider trading.`,
    ` Securities and Exchange Board of India (SEBI) is investigating billionaire Rakesh Jhunjhunwala's alleged insider trading in shares of information technology company Aptech. Jhunjhunwala currently holds 24.24 percent stake in Aptech, which is valued around Rs 160 crore`,
    `India’s second largest IT major Infosys, which hired close to 16,000 freshers in FY21, is planning to hire 15,000 more for the next year.`,
    `The stock saw a massive loss of 16.21 percent on October 22 after a whistle-blowers' complaint spooked investors, shaving Rs 53,451 crore from its market valuation.`,
    `Sharekhan is bullish on Sun Pharmaceutical Industries has recommended buy rating on the stock with a target price of Rs 810 in its research report dated May 27, 2021.`,
    `The company reported weak earnings with a 38 percent fall in revenue.`,
    `Under the terms of the acquisition, for every five shares held in Ranbaxy, shareholders are going to receive four of Sun Pharma.`,
    `Aptech Limited, the global career education and training company, has informed the stock exchanges that its wholly owned subsidiary company has received a dividend of an amount of USD 11,202,479 (equivalent to approximately Rs 50.3 crore) from BJB Career Education Co Ltd of China.`,
    `Infosys, the country's second largest software services company, on Wednesday reported an annual increase of 17 per cent in net profit at ₹ 5,076 crore on the back of large contract wins`,
    ` An ET Now Poll had expected the drug maker to report a profit of Rs 1,030 crore in the quarter`,
    `Net income declined sharply to Rs 87.02 crore in the first quarter of 2020-21 fiscal from Rs 1,417.14 crore in the year-ago period.`,
    `Shares in Ranbaxy Laboratories Ltd fell 3.6 per cent on Wednesday, 27 February 2013, down for a second consecutive session, after India's top drugmaker by sales on reported a surprise quarterly loss on product recall charges.`,
    `The company had posted a consolidated net profit of Rs 3.08 crore in the year-ago quarter, Aptech said in a regulatory filing`,
    `Infosys Insider Trading: Based on an extract of the Structured Digital Database related to the financial results of Infosys for the quarter ended June 30, 2020, the Unpublished Price Sensitive Information (UPSI) came into existence on June 29, 2020. Thus, the UPSI period was from June 29, 2020 to July 15, 2020, Sebi said.`,
    `The development comes after a whistleblower reportedly approached Sebi with a document alleging various irregularities by the company, its promoter Dilip Shanghvi and others, they added.`,
    `Sebi fined Shivani Gupta, Sachin Gupta, Amit Garg and Quick Developers a total of Rs 8 crore for alleged unlawful gains by violating insider trading norms.`,
    `The Securities Appellate Tribunal (SAT) has upheld insider trading charges against VK Kaul, a former independent director of Ranbaxy, and his wife Bala Kaul, accusing them of insider trading.`,
    ` Securities and Exchange Board of India (SEBI) is investigating billionaire Rakesh Jhunjhunwala's alleged insider trading in shares of information technology company Aptech. Jhunjhunwala currently holds 24.24 percent stake in Aptech, which is valued around Rs 160 crore`,
    `India’s second largest IT major Infosys, which hired close to 16,000 freshers in FY21, is planning to hire 15,000 more for the next year.`,
    `The stock saw a massive loss of 16.21 percent on October 22 after a whistle-blowers' complaint spooked investors, shaving Rs 53,451 crore from its market valuation.`,
    `Sharekhan is bullish on Sun Pharmaceutical Industries has recommended buy rating on the stock with a target price of Rs 810 in its research report dated May 27, 2021.`,
    `The company reported weak earnings with a 38 percent fall in revenue.`,
    `Under the terms of the acquisition, for every five shares held in Ranbaxy, shareholders are going to receive four of Sun Pharma.`,
    `Aptech Limited, the global career education and training company, has informed the stock exchanges that its wholly owned subsidiary company has received a dividend of an amount of USD 11,202,479 (equivalent to approximately Rs 50.3 crore) from BJB Career Education Co Ltd of China.`,
    `Infosys, the country's second largest software services company, on Wednesday reported an annual increase of 17 per cent in net profit at ₹ 5,076 crore on the back of large contract wins`,
    ` An ET Now Poll had expected the drug maker to report a profit of Rs 1,030 crore in the quarter`,
    `Net income declined sharply to Rs 87.02 crore in the first quarter of 2020-21 fiscal from Rs 1,417.14 crore in the year-ago period.`,
    `Shares in Ranbaxy Laboratories Ltd fell 3.6 per cent on Wednesday, 27 February 2013, down for a second consecutive session, after India's top drugmaker by sales on reported a surprise quarterly loss on product recall charges.`,
    `The company had posted a consolidated net profit of Rs 3.08 crore in the year-ago quarter, Aptech said in a regulatory filing`,
    `Infosys Insider Trading: Based on an extract of the Structured Digital Database related to the financial results of Infosys for the quarter ended June 30, 2020, the Unpublished Price Sensitive Information (UPSI) came into existence on June 29, 2020. Thus, the UPSI period was from June 29, 2020 to July 15, 2020, Sebi said.`,
    `The development comes after a whistleblower reportedly approached Sebi with a document alleging various irregularities by the company, its promoter Dilip Shanghvi and others, they added.`,
    `Sebi fined Shivani Gupta, Sachin Gupta, Amit Garg and Quick Developers a total of Rs 8 crore for alleged unlawful gains by violating insider trading norms.`,
    `The Securities Appellate Tribunal (SAT) has upheld insider trading charges against VK Kaul, a former independent director of Ranbaxy, and his wife Bala Kaul, accusing them of insider trading.`,
    ` Securities and Exchange Board of India (SEBI) is investigating billionaire Rakesh Jhunjhunwala's alleged insider trading in shares of information technology company Aptech. Jhunjhunwala currently holds 24.24 percent stake in Aptech, which is valued around Rs 160 crore`,
    `India’s second largest IT major Infosys, which hired close to 16,000 freshers in FY21, is planning to hire 15,000 more for the next year.`,
    `The development comes after a whistleblower reportedly approached Sebi with a document alleging various irregularities by the company, its promoter Dilip Shanghvi and others, they added.`,
    `Sebi fined Shivani Gupta, Sachin Gupta, Amit Garg and Quick Developers a total of Rs 8 crore for alleged unlawful gains by violating insider trading norms.`,
    `The Securities Appellate Tribunal (SAT) has upheld insider trading charges against VK Kaul, a former independent director of Ranbaxy, and his wife Bala Kaul, accusing them of insider trading.`,
    ` Securities and Exchange Board of India (SEBI) is investigating billionaire Rakesh Jhunjhunwala's alleged insider trading in shares of information technology company Aptech. Jhunjhunwala currently holds 24.24 percent stake in Aptech, which is valued around Rs 160 crore`,
    `India’s second largest IT major Infosys, which hired close to 16,000 freshers in FY21, is planning to hire 15,000 more for the next year.`
]

module.export = () => {
    return news;
}